package com.kurupdevs.moggr.ui

/**
 * v2.6 flagship: full-app string table — English + Hinglish.
 * Hinglish = Hindi in Roman script, Gen Z bade-bhai tone (warm elder-brother,
 * direct, zero lecture tone). `Strings.s(key, hi)` picks the language;
 * [fmt] fills {placeholders}.
 *
 * EN values mirror the existing on-screen English so nothing regresses.
 */
object Strings {

    fun s(key: String, hi: Boolean): String {
        val table = if (hi) ALL_HI else ALL_EN
        return table[key] ?: ALL_EN[key] ?: key
    }

    fun fmt(key: String, hi: Boolean, vararg args: Pair<String, String>): String {
        var out = s(key, hi)
        for ((k, v) in args) out = out.replace("{$k}", v)
        return out
    }

    // ---------- tab labels ----------
    private val EN = mapOf(
        "tab_home" to "Home",
        "tab_method" to "Method",
        "tab_coach" to "Coach",
        "tab_routine" to "Routine",

        // ---------- home ----------
        "home_welcome_caps" to "WELCOME TO MOGGR",
        "home_hero1" to "Know your face.",
        "home_hero2" to "Own your look.",
        "home_hero_sub" to "Take your 3-angle scan once — your face and report stay saved here.",
        "home_start_scan" to "Start your scan",
        "greet_morning" to "morning",
        "greet_afternoon" to "afternoon",
        "greet_evening" to "evening",
        "greet_night" to "night",
        "greet_good" to "Good {d},",
        "home_hello_name" to "{n} — how's the ascension?",
        "home_hello" to "How's the ascension going?",
        "home_know1" to "Know your face,",
        "home_know2" to "own your rating.",
        "caps_progress" to "PROGRESS",
        "scan_again" to "Scan again",
        "share_btn" to "Share",
        "tip_rescan" to "Tip: rescan every few weeks under the same lighting to track real change.",

        // ---------- method ----------
        "caps_how" to "HOW IT WORKS",
        "method_head1" to "The method,",
        "method_head2" to "no black box.",
        "method_sub" to "Exactly how Moggr turns your photos into a PSL score.",
        "sec_how_scoring" to "How scoring works",
        "scoring_body" to "Your face is measured {n} ways from your 3 photos. Each measurement is scored 1–8 by distance from the community ideal, then grouped into 4 pillars. The pillars combine into your overall PSL. Big deviations cap your tier — one weak area drags the whole score, like community raters tend to judge.",
        "sec_pillars" to "The 4 pillars",
        "pillar_harmony" to "Harmony",
        "pillar_harmony_d" to "How well everything fits together — symmetry, thirds, fifths, midface balance. Raters notice this first.",
        "pillar_features" to "Features",
        "pillar_features_d" to "The individual pieces — eyes, nose, lips, brows, cheekbones.",
        "pillar_dimorphism" to "Dimorphism",
        "pillar_dimorphism_d" to "Structure cues — jaw width, chin, brow area.",
        "pillar_angularity" to "Angularity",
        "pillar_angularity_d" to "Sharp vs soft — jaw angle, cheek definition.",
        "sec_measurements" to "The {n} measurements",
        "sec_tiers" to "The tiers",
        "tier_desc_0" to "Gigachad — near-mythical",
        "tier_desc_1" to "Chad",
        "tier_desc_2" to "Chadlite",
        "tier_desc_3" to "HTN — High Tier Normie",
        "tier_desc_4" to "MTN — Mid Tier Normie",
        "tier_desc_5" to "LTN — Low Tier Normie",
        "tier_desc_6" to "Sub-5 — maximum ascension potential",
        "tiers_note" to "Tiers are looksmaxxing-community conventions, not medical grades.",
        "caps_accurate" to "For an accurate scan",
        "scan_tip_0" to "Neutral expression, mouth closed, no smile.",
        "scan_tip_1" to "Camera at eye level, arm's length away.",
        "scan_tip_2" to "Even lighting on the face — no harsh shadows.",
        "scan_tip_3" to "Hair off the forehead, nothing covering the jaw.",
        "scan_tip_4" to "Look straight ahead for front, full 90° turn for profiles.",
        "caps_honest" to "Honest limits",
        "honest_body" to "PSL ratios are forum conventions, not validated science. Scores shift with lighting, pose, lens and expression — same setup gives comparable results. A number from your camera is a starting point for the stuff you control (skin, hair, fitness, style, posture), not a verdict on your worth.",

        // ---------- method: grooming by budget (v2.6 price tiers) ----------
        "caps_budget" to "GROOMING BY BUDGET",
        "budget_head1" to "Ascend,",
        "budget_head2" to "at any budget.",
        "budget_sub" to "Free habits do 80% of the work. Products only polish.",
        "tier_free_title" to "₹0 — Free forever",
        "tier_free_sub" to "Zero rupees. Just discipline.",
        "free_0_name" to "Water",
        "free_0_desc" to "2–3 litres daily — debloats the face, clears skin.",
        "free_1_name" to "Sleep",
        "free_1_desc" to "7–9 hrs on a schedule — puffy eyes and dull skin are usually a sleep problem.",
        "free_2_name" to "Ice / cold rinse",
        "free_2_desc" to "Cold water face rinse in the morning — tightens skin, drops morning puff.",
        "free_3_name" to "Posture",
        "free_3_desc" to "Chin tucks + screens at eye level — free jawline, zero rupees.",
        "tier_100_title" to "₹100 — Budget picks",
        "tier_100_sub" to "Pocket-money skincare that actually works.",
        "b100_0_name" to "Himalaya neem face wash",
        "b100_0_desc" to "Gentle daily cleanser — a pea-size drop, morning + night.",
        "b100_1_name" to "Nivea creme (blue tin)",
        "b100_1_desc" to "Classic all-rounder moisturizer — thin layer on damp skin.",
        "b100_2_name" to "Coconut oil",
        "b100_2_desc" to "Hair + scalp oiling before wash — desi classic for a reason.",
        "b100_3_name" to "Lip balm",
        "b100_3_desc" to "Any basic one — cracked lips kill photos.",
        "tier_500_title" to "₹500 — Level-up picks",
        "tier_500_sub" to "Simple, safe basics from trusted Indian brands.",
        "b500_0_name" to "Minimalist gentle cleanser",
        "b500_0_desc" to "Simple daily face wash — no harsh foam, no fragrance drama.",
        "b500_1_name" to "Dot & Key gel moisturizer",
        "b500_1_desc" to "Lightweight gel — good for oily/combo Indian skin.",
        "b500_2_name" to "Sunscreen SPF 50",
        "b500_2_desc" to "No-white-cast gel type — the single highest-ROI skincare step.",
        "b500_3_name" to "Satin pillowcase",
        "b500_3_desc" to "Less frizz, fewer sleep lines — a cheap sleep upgrade.",
        "budget_note" to "Prices are approximate Indian MRPs. Patch-test anything new; if skin keeps acting up, that's a dermatologist visit — not more products.",

        // ---------- routine ----------
        "caps_90" to "90-DAY ASCENSION",
        "plan_head1" to "The plan,",
        "plan_head2" to "day by day.",
        "plan_sub" to "Built from your scan — your weakest areas get the most reps.",
        "day_phase" to "Day {d} / 90 · Phase {p}: {t}",
        "this_week" to "This week: {w}",
        "streak_days" to "{n}-day streak",
        "today_count" to "{d}/{t} today",
        "caps_today" to "TODAY'S PLAN",
        "all_done" to "All done today. Consistency is the whole game.",
        "jaw_caps" to "JAW SESSION",
        "jaw_title" to "10-min gum timer",
        "jaw_detail" to "Chew evenly on both sides — not just your strong side.",
        "jaw_start" to "Start",
        "jaw_pause" to "Pause",
        "jaw_resume" to "Resume",
        "jaw_reset" to "Reset",
        "jaw_tmj" to "Stop if your jaw clicks or hurts — pushing through pain is how TMJ starts.",
        "jaw_logged" to "Logged for today — nice work.",
        "cat_skin" to "Skin",
        "cat_hair" to "Hair",
        "cat_posture" to "Posture",
        "cat_sleep" to "Sleep",
        "cat_debloat" to "Debloat",
        "cat_jaw" to "Jaw",
        "cat_style" to "Style",

        // routine tasks (id → title / detail)
        "task_cleanse_t" to "Morning cleanse",
        "task_cleanse_d" to "Lukewarm water + gentle cleanser",
        "task_sunscreen_t" to "Sunscreen",
        "task_sunscreen_d" to "SPF 30+ on face and neck",
        "task_moisturize_t" to "Moisturize",
        "task_moisturize_d" to "Morning and night, every day",
        "task_posture_t" to "Posture drills",
        "task_posture_d" to "10 min — chin tucks + wall angels",
        "task_tongue_t" to "Tongue posture",
        "task_tongue_d" to "10 min — whole tongue resting on palate",
        "task_water_t" to "Hydrate",
        "task_water_d" to "2+ litres of water through the day",
        "task_water_u" to "glasses",
        "task_sleep_t" to "Sleep 7–8 hrs",
        "task_sleep_d" to "No screens 30 min before bed",
        "task_nojunk_t" to "Clean eating",
        "task_nojunk_d" to "No junk food or excess sugar today",
        "task_morning_depuff_t" to "Morning de-puff",
        "task_morning_depuff_d" to "Cold spoon or cold water 2 min on puffy areas",
        "task_sleep_window_t" to "Sleep window",
        "task_sleep_window_d" to "In bed by 11 — same time every night",
        "task_neck_curls_t" to "Neck curls",
        "task_neck_curls_d" to "Bodyweight neck curls build the frame around your jaw",
        "task_neck_curls_u" to "sets",
        "task_chin_tucks_t" to "Chin tucks",
        "task_chin_tucks_d" to "10 reps, 5s holds — fixes forward head posture",
        "task_wall_angels_t" to "Wall angels",
        "task_wall_angels_d" to "2x10 — opens the chest, stacks the spine",
        "task_hair_care_t" to "Hair check",
        "task_hair_care_d" to "Scalp cleanse today — is your cut working for your face?",
        "task_groom_t" to "Grooming day",
        "task_groom_d" to "Brows tidy, nails short, clean lineup",
        "task_fit_check_t" to "Fit check",
        "task_fit_check_d" to "One outfit that actually fits your frame",
        "task_photo_practice_t" to "Photo practice",
        "task_photo_practice_d" to "Front photo, same light as your scan, neutral face",
        "task_chew_gum_t" to "Gum session",
        "task_chew_gum_d" to "10 min, chew evenly both sides. Stop if your jaw clicks or hurts.",
        "task_chew_gum_u" to "min"
    )

    /** Coach strings. */
    fun coach(key: String, hi: Boolean): String = s("coach_$key", hi)

    /** Append coach keys into EN via a second map (kept separate for readability). */
    private val EN2 = mapOf(
        "coach_title" to "Moggr Coach",
        "coach_sub" to "Looksmaxing AI · softmaxxing guidance · {v}",
        "coach_placeholder" to "Ask about jawline, skin, hair…",
        "coach_send" to "Send",
        "coach_typing" to "Coach is typing…",
        "coach_fallback" to "Coach is resting right now — the free API didn't answer. Try again in a bit.",
        "coach_offline_note" to "Coach runs on a free API — replies can be slow. Your photos never leave your phone; only your questions and measurement numbers may be sent to the AI service.",
        "coach_greet_scan" to "Yo {n} — I'm Moggr's Looksmaxing AI. I see your scan: {p} PSL. Ask me anything — what's dragging your score, what to fix first, hair, skin, photos. Or send a fresh photo and I'll break it down.",
        "coach_greet" to "Yo — I'm Moggr's Looksmaxing AI. No scan on file yet, but ask me anything about looksmaxxing: jawline, skin, hair, posture, photos. Or send a photo and I'll scan it on your phone and break it down.",
        "coach_back" to "‹ Back",
        "coach_vibe_blunt" to "blunt & honest",
        "coach_vibe_bigbro" to "warm big-bro mode",
        "coach_vibe_hype" to "hype mode",
        "coach_checkin_title" to "Morning check-in",
        "coach_checkin_sleep" to "Sleep last night",
        "coach_checkin_puff" to "Face puffiness",
        "coach_checkin_focus" to "Today's #1 focus",
        "coach_checkin_skip" to "Skip",
        "coach_checkin_log" to "Log it",
        "coach_flow_title" to "Diagnose my weakest trait",
        "coach_flow_sub" to "Find what's dragging your score",
        "coach_plan_title" to "Build my 7-day plan",
        "coach_plan_sub" to "One week, day by day",
        "coach_photo_title" to "Fix my photos",
        "coach_photo_sub" to "Angles, light, presence",

        // ---------- guides ----------
        "caps_glowup" to "GLOW-UP CARDS",
        "swipe_next" to "Swipe for the next card",
        "glowup_0" to "Glow-Up Tips",
        "glowup_1" to "Face Wash Technique",
        "glowup_2" to "Fresh Breath Routine",
        "glowup_3" to "Backpack Posture Reset",
        "glowup_4" to "Outfit Fit Guide",
        "glowup_5" to "Shoe Cleanup Guide",
        "caps_winter" to "WINTER ARC",
        "winter_title" to "Winter Arc Ascension",
        "winter_sub" to "Tap to open the slides",
        "winter_slide_0" to "Best Winter Arc Ascension Guide",
        "winter_slide_1" to "Hunter Eyes",
        "winter_slide_2" to "Depuff: Lymphatic Drainage",
        "winter_slide_3" to "Jawline Through Mewing",
        "caps_hair" to "HAIR & STYLING",
        "hair_no_scan" to "Take a scan to get your shape-matched cut. General guide below:",
        "hair_your_cut" to "Your cut: {s} face",
        "hair_matched_sub" to "Matched from your scan.",
        "hair_other" to "Other face shapes",
        "barber_title" to "What to tell your barber",
        "barber_sub" to "Copy-paste script for the chair.",
        "barber_script" to "\"3 on the sides, scissors on top, keep some length to style, taper the neckline, clean up the edges.\"",
        "barber_b1" to "Bring a photo of the cut you want — words mean different things to different barbers.",
        "barber_b2" to "If it feels off halfway through, speak up then — not after.",
        "curly_title" to "Curly hair playbook",
        "curly_sub" to "Curls need a different routine, not more products.",
        "curly_b0" to "Wash 2x a week with sulfate-free shampoo — daily washing dries curls out.",
        "curly_b1" to "Condition every wash, then leave-in conditioner on damp hair.",
        "curly_b2" to "Never brush dry curls — detangle wet with fingers or a wide-tooth comb.",
        "curly_b3" to "Sleep on a satin pillowcase to cut overnight frizz.",
        "curly_b4" to "Less heat, more patience — curls reward consistency.",
        "style_title" to "5-minute styling routine",
        "style_sub" to "The daily minimum that actually works.",
        "style_s0" to "Damp hair",
        "style_s0d" to "Start with towel-dried, slightly damp hair — never soaking, never dry.",
        "style_s1" to "Pea-size product",
        "style_s1d" to "Matte clay for texture, cream for a neat look. Less than you think.",
        "style_s2" to "Blow direction",
        "style_s2d" to "Blow-dry in the direction you want it to sit — heat sets the shape.",
        "style_s3" to "Finish",
        "style_s3d" to "Style with fingers, not a comb, for a natural finish. Done.",
        "hair_shape_oval" to "Most cuts work — your proportions are already balanced. Textured crop or a clean side part, don't fight what you have.",
        "hair_shape_round" to "Height on top, faded short sides. Avoid bowl cuts and anything that adds width at the cheeks.",
        "hair_shape_square" to "Soften the angles with texture on top and a messy fringe. Very short buzz cuts make the jaw look boxier.",
        "hair_shape_oblong" to "Avoid extra height on top. A side part with fuller sides keeps the face from looking longer.",
        "hair_shape_heart" to "Volume around the jaw balances a wider forehead. Textured fringe, medium length.",
        "hair_shape_diamond" to "Fringe plus width at the forehead and jawline. Avoid cuts that collapse flat on the sides.",

        // skin quiz
        "caps_skin" to "SKIN QUIZ",
        "skinq_title" to "Find your 3-step routine",
        "skinq_sub" to "Tap one option per question — takes 20 seconds.",
        "sq0" to "By midday, your skin feels…",
        "sq0_o0" to "Shiny / greasy",
        "sq0_o1" to "Tight",
        "sq0_o2" to "Shiny only on the T-zone",
        "sq0_o3" to "Comfortable",
        "sq1" to "Does your skin react easily?",
        "sq1_o0" to "Yes — goes red / itchy often",
        "sq1_o1" to "Sometimes",
        "sq1_o2" to "Nope, pretty chill",
        "sq2" to "How often do you break out?",
        "sq2_o0" to "Often",
        "sq2_o1" to "Sometimes",
        "sq2_o2" to "Rarely",
        "sq3" to "Sun time on a normal day?",
        "sq3_o0" to "Mostly indoors",
        "sq3_o1" to "1–2 hrs outside",
        "sq3_o2" to "Long hours outside",
        "sq4" to "Budget for the full routine?",
        "sq4_o0" to "Under ₹300",
        "sq4_o1" to "₹300–800",
        "sq4_o2" to "₹800+",
        "skin_result_title" to "YOUR 3-STEP",
        "skin_result_sub" to "Morning + night. Same three steps, every day.",
        "skin_step_cleanser" to "Cleanser",
        "skin_step_moist" to "Moisturizer",
        "skin_step_spf" to "SPF 30+",
        "skin_cleanser_oily" to "Gel or light foaming cleanser — skip the heavy cream washes.",
        "skin_cleanser_dry" to "Gentle cream or milky cleanser — avoid foaming 'deep clean' ones.",
        "skin_cleanser_combo" to "Gentle gel cleanser — light for the T-zone, kind to the cheeks.",
        "skin_cleanser_normal" to "Any gentle cleanser — keep it simple.",
        "skin_moist_oily" to "Lightweight gel moisturizer — skip the heavy creams.",
        "skin_moist_dry" to "Richer cream moisturizer — your skin will drink it up.",
        "skin_moist_combo" to "Light lotion or gel-cream texture.",
        "skin_moist_normal" to "A basic light moisturizer.",
        "skin_spf_high" to "SPF 30+ every morning, reapplied every 3 hrs outdoors — carry it with you.",
        "skin_spf_sensitive" to "SPF 30+ every morning — go fragrance-free if your skin reacts.",
        "skin_spf_default" to "SPF 30+ every morning — the single highest-ROI skincare step.",
        "skin_extra_sensitive" to "Fragrance-free everything — your skin votes no on fragrance.",
        "skin_extra_acne" to "Keep it boring: cleanser, moisturizer, SPF. More products do not mean faster clear skin — persistent acne is a dermatologist visit, not more serums.",
        "skin_extra_budget" to "Budget route: one gentle cleanser + one moisturizer + one sunscreen is the whole routine. Skip serums until the basics are daily.",
        "retake_quiz" to "Retake quiz",
        "spf_title" to "Desi no-white-cast sunscreen guide",
        "spf_sub" to "Why sunscreen looks ashy on brown skin — and how to dodge it.",
        "spf_b0" to "Chemical vs mineral: chemical filters absorb UV and usually blend invisibly; mineral filters (zinc, titanium) sit on top and reflect light — that white layer is the cast.",
        "spf_b1" to "On brown skin, chemical or hybrid gel sunscreens disappear. Mineral-only ones almost always leave a grey/white cast.",
        "spf_b2" to "Reapply every 3 hrs when you're outdoors — one morning layer doesn't survive the day.",
        "spf_b3" to "Indian-market tips: look for gel sunscreens labelled 'no white cast'; skip thick white creams unless the label says otherwise; a 50g tube covers about a month of daily face use.",

        // debloat
        "caps_debloat" to "DEBLOAT PROTOCOL",
        "debloat_sub" to "A 7-day morning plan to drop face puffiness. Tap a day to open its checklist.",
        "debloat_d0t" to "Water reset",
        "debloat_d0i0" to "Drink 500ml water right after waking up",
        "debloat_d0i1" to "No pickles / achaar today",
        "debloat_d0i2" to "Finish dinner 3 hrs before bed",
        "debloat_d1t" to "Sodium audit",
        "debloat_d1i0" to "Skip papad and instant noodles today",
        "debloat_d1i1" to "Read one namkeen packet's sodium label — you'll be shocked",
        "debloat_d1i2" to "Drink water with every meal",
        "debloat_d2t" to "Potassium day",
        "debloat_d2i0" to "Eat a banana and drink coconut water",
        "debloat_d2i1" to "Add palak to one meal",
        "debloat_d2i2" to "No restaurant food today",
        "debloat_d3t" to "Sleep push",
        "debloat_d3i0" to "Get 8 hrs of sleep tonight",
        "debloat_d3i1" to "No chai / coffee after 4pm",
        "debloat_d3i2" to "Last meal 3 hrs before bed",
        "debloat_d4t" to "Lymph day",
        "debloat_d4i0" to "5-min morning lymphatic massage: gentle strokes from jaw → down the neck → to the collarbones",
        "debloat_d4i1" to "Cold water face rinse after",
        "debloat_d4i2" to "Keep sodium low today",
        "debloat_d5t" to "Restaurant rules",
        "debloat_d5i0" to "If eating out: skip the heavy gravies, ask for less salt",
        "debloat_d5i1" to "Dahi + cucumber with dinner",
        "debloat_d5i2" to "Walk 15 mins after dinner",
        "debloat_d6t" to "Photo check-in",
        "debloat_d6i0" to "Take a photo in the same lighting and angle as Day 1",
        "debloat_d6i1" to "Compare — keep what worked as daily habits",
        "debloat_d6i2" to "This is education, not a crash plan — debloat is a habit, not a week",
        "sod_title" to "Desi Sodium Guide",
        "sod_sub" to "Salt hides in desi staples — here's where.",
        "sod_high" to "HIGH SODIUM — go easy",
        "sod_h0" to "Pickles / achaar — one spoonful can carry half a day's salt",
        "sod_h1" to "Papad — roasted or fried, both are salt bombs",
        "sod_h2" to "Instant noodles — the masala sachet is the culprit",
        "sod_h3" to "Chips & namkeen — portion it out, never eat from the bag",
        "sod_h4" to "Restaurant gravies — loaded with butter and salt",
        "sod_low" to "DEBLOAT FRIENDLY — eat more",
        "sod_l0" to "Banana — potassium helps flush excess sodium",
        "sod_l1" to "Coconut water — hydration + potassium",
        "sod_l2" to "Palak — potassium-rich, low sodium",
        "sod_l3" to "Dahi — light, keeps digestion calm",
        "sod_l4" to "Cucumber — water-rich and cooling",

        // posture
        "caps_posture" to "POSTURE CHALLENGE",
        "posture_sub" to "30 days to fix forward head posture — the silent jawline killer. Tick weeks as you finish them.",
        "posture_w0" to "Week 1 — Foundation",
        "posture_w0i0" to "Chin tucks: 10 reps × 5-second hold, every day",
        "posture_w0i1" to "Raise your screen to eye level — stop craning down at your phone",
        "posture_w0i2" to "Catch yourself jutting your head forward, pull it back",
        "posture_w1" to "Week 2 — Open up",
        "posture_w1i0" to "Keep the chin tucks going daily",
        "posture_w1i1" to "Wall angels: 3 × 10 — back flat against the wall",
        "posture_w1i2" to "Un-hunch your shoulders once every hour",
        "posture_w2" to "Week 3 — Chest reset",
        "posture_w2i0" to "Doorway chest stretch: 2 × 30s per side",
        "posture_w2i1" to "Keep screens at eye level — the habit from Week 1",
        "posture_w2i2" to "Sleep on your back when you can",
        "posture_w3" to "Week 4 — Lock it in",
        "posture_w3i0" to "Full combo daily: chin tucks + wall angels + doorway stretch",
        "posture_w3i1" to "Posture is maintenance now — the hard part was starting",
        "posture_foot" to "Full habit tracking lives in the Routine tab — this is the challenge plan.",

        // season quiz
        "caps_season" to "COLOR SEASON",
        "season_title" to "Find your season",
        "season_sub" to "3 questions — wear the colors that make your skin look alive.",
        "season_q0" to "Check your wrist veins in daylight",
        "season_q0w" to "Look green",
        "season_q0c" to "Look blue / purple",
        "season_q1" to "Which jewelry looks better on you?",
        "season_q1w" to "Gold",
        "season_q1c" to "Silver",
        "season_q2" to "What happens in the sun?",
        "season_q2w" to "Tan easily",
        "season_q2c" to "Burn first",
        "season_you_are" to "You are {s}",
        "season_tagline_autumn" to "Warm, deep, earthy — you glow in rich tones.",
        "season_tagline_winter" to "Cool, bold, high-contrast — black and jewel tones are yours.",
        "season_tagline_spring" to "Warm, bright, fresh — light punchy colors lift you.",
        "season_tagline_summer" to "Cool, soft, muted — powdery pastels suit you best.",
        "season_tagline_neutral" to "You sit between warm and cool — borrow from both sides and wear what you already get compliments in.",
        "season_name_autumn" to "Autumn",
        "season_name_winter" to "Winter",
        "season_name_spring" to "Spring",
        "season_name_summer" to "Summer",
        "season_name_neutral" to "In-between",
        "caps_desi_palette" to "DESI PALETTE",
        "season_tip" to "Start with one piece in your palette near your face — a tee, a kurta, a shirt. Watch how your skin looks in daylight.",
        "swatch_title" to "Swatch test — the honest drape",
        "swatch_b0" to "Stand in daylight facing a window. Hold a solid-color cloth under your chin — mustard or yellow for the warm test, grey or blue for the cool test.",
        "swatch_b1" to "Watch your jawline shadows and your skin: if the shadows sharpen and your skin looks alive, that temperature suits you. If your skin looks dull or grey, it's not yours. Two cloths, two minutes — no app filter can fake this.",
        "caps_color_season" to "YOUR COLOR SEASON",
        "season_locked" to "No undertone read yet — take the 3-question season quiz in the Guides tab to unlock your palette.",
        "caps_softmaxx" to "SOFTMAXX GUIDES",
        "softmaxx_sub" to "Every method Moggr recommends, in plain words. Tap a guide to read it.",

        // ---------- camera / scan ----------
        "cam_analyze" to "Analyze my face",
        "cam_retake" to "Retake",
        "cam_analyzing" to "Analyzing your face",

        // ---------- result ----------
        "caps_face_report" to "FACE REPORT",
        "sec_feature_scores" to "Feature scores",
        "sec_positives" to "Positives",
        "sec_negatives" to "Negatives",
        "sec_ascension" to "Ascension plan",
        "sec_summary" to "Summary",
        "result_next" to "NEXT",
        "face_map" to "Face map"
    )

    /** Hinglish: Hindi in Roman script, Gen Z bade-bhai tone. */
    private val HI = mapOf(
        "tab_home" to "Home",
        "tab_method" to "Method",
        "tab_coach" to "Coach",
        "tab_routine" to "Routine",

        "home_welcome_caps" to "MOGGR MEIN SWAGAT",
        "home_hero1" to "Apna face jaan.",
        "home_hero2" to "Apna look own kar.",
        "home_hero_sub" to "Ek baar 3-angle scan kar le — tera face aur report yahin save rahenge.",
        "home_start_scan" to "Scan shuru kar",
        "greet_morning" to "Subah",
        "greet_afternoon" to "Dopahar",
        "greet_evening" to "Shaam",
        "greet_night" to "Raat",
        "greet_good" to "{d},",
        "home_hello_name" to "{n} — ascension kaisa chal raha?",
        "home_hello" to "Ascension kaisa chal raha?",
        "home_know1" to "Face ko jaan,",
        "home_know2" to "rating ko own kar.",
        "caps_progress" to "PROGRESS",
        "scan_again" to "Phir se scan",
        "share_btn" to "Share",
        "tip_rescan" to "Tip: har kuch hafte same lighting me rescan kar — asli change track hoga.",

        "caps_how" to "KAISE KAAM KARTA HAI",
        "method_head1" to "Method,",
        "method_head2" to "koi black box nahi.",
        "method_sub" to "Moggr teri photos ko PSL score me kaise badalta hai — bilkul saaf saaf.",
        "sec_how_scoring" to "Scoring kaise hoti hai",
        "scoring_body" to "Teri 3 photos se face {n} tareekon se measure hota hai. Har measurement community ideal se kitni door hai us hisab se 1-8 score milta hai, phir 4 pillars me group hota hai. Pillars milke overall PSL banta hai. Bade deviations tier cap kar dete hain — ek weak area poora score neeche kheench leta hai, jaise community raters judge karte hain.",
        "sec_pillars" to "4 pillars",
        "pillar_harmony" to "Harmony",
        "pillar_harmony_d" to "Sab kuch kitna fit baithta hai — symmetry, thirds, fifths, midface balance. Rater sabse pehle yehi dekhte hain.",
        "pillar_features" to "Features",
        "pillar_features_d" to "Alag alag pieces — eyes, nose, lips, brows, cheekbones.",
        "pillar_dimorphism" to "Dimorphism",
        "pillar_dimorphism_d" to "Structure ke cues — jaw width, chin, brow area.",
        "pillar_angularity" to "Angularity",
        "pillar_angularity_d" to "Sharp vs soft — jaw angle, cheek definition.",
        "sec_measurements" to "{n} measurements",
        "sec_tiers" to "Tiers",
        "tier_desc_0" to "Gigachad — lagbhag mythical",
        "tier_desc_1" to "Chad",
        "tier_desc_2" to "Chadlite",
        "tier_desc_3" to "HTN — High Tier Normie",
        "tier_desc_4" to "MTN — Mid Tier Normie",
        "tier_desc_5" to "LTN — Low Tier Normie",
        "tier_desc_6" to "Sub-5 — maximum ascension potential",
        "tiers_note" to "Ye tiers looksmaxxing community ke conventions hain, medical grades nahi.",
        "caps_accurate" to "ACCURATE SCAN KE LIYE",
        "scan_tip_0" to "Neutral expression, muh band, no smile.",
        "scan_tip_1" to "Camera eye level pe, haath ki doori pe.",
        "scan_tip_2" to "Face pe even lighting — tez shadows nahi.",
        "scan_tip_3" to "Baal maathe se hata, jaw pe kuch cover na ho.",
        "scan_tip_4" to "Front ke liye seedha dekho, profile ke liye poora 90° turn.",
        "caps_honest" to "HONEST LIMITS",
        "honest_body" to "PSL ratios forum conventions hain, validated science nahi. Lighting, pose, lens aur expression se score badalta hai — same setup me comparable results milte hain. Camera ka number un cheezon ka starting point hai jo tere control me hain (skin, hair, fitness, style, posture), teri worth ka verdict nahi.",

        "caps_budget" to "BUDGET KE HISAB SE GROOMING",
        "budget_head1" to "Ascend,",
        "budget_head2" to "kisi bhi budget pe.",
        "budget_sub" to "Free habits 80% kaam karte hain. Products sirf polish karte hain.",
        "tier_free_title" to "₹0 — Bilkul free",
        "tier_free_sub" to "Zero rupaye. Sirf discipline.",
        "free_0_name" to "Paani",
        "free_0_desc" to "Roz 2-3 litre — face debloat hota hai, skin clear hoti hai.",
        "free_1_name" to "Neend",
        "free_1_desc" to "7-9 ghante fixed time pe — puffy eyes aur dull skin aam taur pe neend ki problem hai.",
        "free_2_name" to "Baraf / thanda paani",
        "free_2_desc" to "Subah thande paani se muh dho — skin tight, subah ki puffiness gayab.",
        "free_3_name" to "Posture",
        "free_3_desc" to "Chin tucks + screen eye level pe — free jawline, zero rupaye.",
        "tier_100_title" to "₹100 — Budget picks",
        "tier_100_sub" to "Pocket-money skincare jo sach me kaam karti hai.",
        "b100_0_name" to "Himalaya neem face wash",
        "b100_0_desc" to "Gentle daily cleanser — matar-dana jitna, subah + raat.",
        "b100_1_name" to "Nivea creme (neela dabba)",
        "b100_1_desc" to "Classic all-rounder moisturizer — halki geeli skin pe patli layer.",
        "b100_2_name" to "Nariyal tel",
        "b100_2_desc" to "Wash se pehle baalon + scalp me tel — desi classic, wajah se hai.",
        "b100_3_name" to "Lip balm",
        "b100_3_desc" to "Koi bhi basic — phate honth photos kharab karte hain.",
        "tier_500_title" to "₹500 — Level-up picks",
        "tier_500_sub" to "Trusted Indian brands ke simple, safe basics.",
        "b500_0_name" to "Minimalist ka gentle cleanser",
        "b500_0_desc" to "Simple daily face wash — tez jhaag nahi, fragrance ka drama nahi.",
        "b500_1_name" to "Dot & Key ka gel moisturizer",
        "b500_1_desc" to "Halka gel — oily/combo Indian skin ke liye badhiya.",
        "b500_2_name" to "Sunscreen SPF 50",
        "b500_2_desc" to "No-white-cast gel type — skincare ka sabse high-ROI step.",
        "b500_3_name" to "Satin ka takiya cover",
        "b500_3_desc" to "Kam frizz, kam sleep-lines — sasta sleep upgrade.",
        "budget_note" to "Prices lagbhag Indian MRP hain. Nayi cheez patch-test kar; skin lagatar kharab rahe to dermatologist ke paas ja — aur products nahi.",

        "caps_90" to "90-DIN KA ASCENSION",
        "plan_head1" to "Plan,",
        "plan_head2" to "din-ba-din.",
        "plan_sub" to "Tere scan se bana — sabse weak areas ko sabse zyada reps.",
        "day_phase" to "Din {d} / 90 · Phase {p}: {t}",
        "this_week" to "Is hafte: {w}",
        "streak_days" to "{n} din ki streak",
        "today_count" to "aaj {d}/{t}",
        "caps_today" to "AAJ KA PLAN",
        "all_done" to "Aaj sab done. Consistency hi poora game hai.",
        "jaw_caps" to "JAW SESSION",
        "jaw_title" to "10-min gum timer",
        "jaw_detail" to "Dono sides pe barabar chaba — sirf strong side pe nahi.",
        "jaw_start" to "Start",
        "jaw_pause" to "Ruk ja",
        "jaw_resume" to "Phir se",
        "jaw_reset" to "Reset",
        "jaw_tmj" to "Jaw click kare ya dard ho to ruk ja — dard me zor lagana hi TMJ ki shuruaat hai.",
        "jaw_logged" to "Aaj ke liye logged — badhiya kaam.",
        "cat_skin" to "Skin",
        "cat_hair" to "Baal",
        "cat_posture" to "Posture",
        "cat_sleep" to "Neend",
        "cat_debloat" to "Debloat",
        "cat_jaw" to "Jaw",
        "cat_style" to "Style",

        "task_cleanse_t" to "Subah ka cleanse",
        "task_cleanse_d" to "Halka garam paani + gentle cleanser",
        "task_sunscreen_t" to "Sunscreen",
        "task_sunscreen_d" to "Face aur gardan pe SPF 30+",
        "task_moisturize_t" to "Moisturize",
        "task_moisturize_d" to "Subah aur raat, roz",
        "task_posture_t" to "Posture drills",
        "task_posture_d" to "10 min — chin tucks + wall angels",
        "task_tongue_t" to "Tongue posture",
        "task_tongue_d" to "10 min — poori jeebh taalu pe tika ke",
        "task_water_t" to "Paani piyo",
        "task_water_d" to "Din bhar me 2+ litre paani",
        "task_water_u" to "glass",
        "task_sleep_t" to "7-8 ghante so",
        "task_sleep_d" to "Sone se 30 min pehle no screens",
        "task_nojunk_t" to "Saaf khana",
        "task_nojunk_d" to "Aaj no junk food, zyada meetha nahi",
        "task_morning_depuff_t" to "Subah ka de-puff",
        "task_morning_depuff_d" to "Puffy areas pe thanda chammach ya thanda paani 2 min",
        "task_sleep_window_t" to "Sone ka time",
        "task_sleep_window_d" to "11 baje tak bistar — roz same time",
        "task_neck_curls_t" to "Neck curls",
        "task_neck_curls_d" to "Bodyweight neck curls jaw ke aas-paas frame banate hain",
        "task_neck_curls_u" to "sets",
        "task_chin_tucks_t" to "Chin tucks",
        "task_chin_tucks_d" to "10 reps, 5s hold — forward head posture fix karta hai",
        "task_wall_angels_t" to "Wall angels",
        "task_wall_angels_d" to "2x10 — chest khulta hai, spine seedhi",
        "task_hair_care_t" to "Baal check",
        "task_hair_care_d" to "Aaj scalp cleanse — kya cut tere face pe suit kar raha?",
        "task_groom_t" to "Grooming day",
        "task_groom_d" to "Brows tidy, nails chhote, clean lineup",
        "task_fit_check_t" to "Fit check",
        "task_fit_check_d" to "Ek outfit jo tere frame pe actually fit ho",
        "task_photo_practice_t" to "Photo practice",
        "task_photo_practice_d" to "Front photo, scan wali light me, neutral face",
        "task_chew_gum_t" to "Gum session",
        "task_chew_gum_d" to "10 min, dono sides barabar. Jaw click kare ya dard ho to ruk ja.",
        "task_chew_gum_u" to "min"
    )

    /** Hinglish for the coach + guides tables. */
    private val HI2 = mapOf(
        "coach_title" to "Moggr Coach",
        "coach_sub" to "Looksmaxing AI · softmaxxing guidance · {v}",
        "coach_placeholder" to "Jawline, skin, baal… ke baare me puch",
        "coach_send" to "Bhej",
        "coach_typing" to "Coach likh raha hai…",
        "coach_fallback" to "Coach abhi rest kar raha hai — free API ne jawab nahi diya. Thodi der me phir try kar.",
        "coach_offline_note" to "Coach free API pe chalta hai — reply slow ho sakta hai. Teri photos kabhi phone se bahar nahi jaati; sirf tere sawal aur measurement numbers AI service ko ja sakte hain.",
        "coach_greet_scan" to "Yo {n} — main Moggr ka Looksmaxing AI hoon. Tera scan dekha: {p} PSL. Kuch bhi puch — score kya kheench raha hai, pehle kya fix karein, baal, skin, photos. Ya fresh photo bhej, main breakdown kar dunga.",
        "coach_greet" to "Yo — main Moggr ka Looksmaxing AI hoon. Abhi scan nahi hai, par looksmaxxing pe kuch bhi puch: jawline, skin, baal, posture, photos. Ya photo bhej, phone pe scan karke breakdown dunga.",
        "coach_back" to "‹ Wapas",
        "coach_vibe_blunt" to "seedha & honest",
        "coach_vibe_bigbro" to "bade bhai mode",
        "coach_vibe_hype" to "hype mode",
        "coach_checkin_title" to "Subah ka check-in",
        "coach_checkin_sleep" to "Raat ki neend",
        "coach_checkin_puff" to "Face ki puffiness",
        "coach_checkin_focus" to "Aaj ka #1 focus",
        "coach_checkin_skip" to "Chhod",
        "coach_checkin_log" to "Log kar",
        "coach_flow_title" to "Mera weakest trait diagnose kar",
        "coach_flow_sub" to "Score kya kheench raha hai, dhoondh",
        "coach_plan_title" to "Mera 7-din ka plan bana",
        "coach_plan_sub" to "Ek hafta, din-ba-din",
        "coach_photo_title" to "Meri photos fix kar",
        "coach_photo_sub" to "Angles, light, presence",

        "caps_glowup" to "GLOW-UP CARDS",
        "swipe_next" to "Agla card dekhne ke liye swipe kar",
        "glowup_0" to "Glow-Up Tips",
        "glowup_1" to "Face Wash Technique",
        "glowup_2" to "Fresh Breath Routine",
        "glowup_3" to "Backpack Posture Reset",
        "glowup_4" to "Outfit Fit Guide",
        "glowup_5" to "Shoe Cleanup Guide",
        "caps_winter" to "WINTER ARC",
        "winter_title" to "Winter Arc Ascension",
        "winter_sub" to "Slides kholne ke liye tap kar",
        "winter_slide_0" to "Best Winter Arc Ascension Guide",
        "winter_slide_1" to "Hunter Eyes",
        "winter_slide_2" to "Depuff: Lymphatic Drainage",
        "winter_slide_3" to "Jawline Through Mewing",
        "caps_hair" to "BAAL & STYLING",
        "hair_no_scan" to "Shape-matched cut ke liye scan kar. Neeche general guide hai:",
        "hair_your_cut" to "Tera cut: {s} face",
        "hair_matched_sub" to "Tere scan se match kiya.",
        "hair_other" to "Doosre face shapes",
        "barber_title" to "Naai ko kya bolna hai",
        "barber_sub" to "Chair ke liye copy-paste script.",
        "barber_script" to "\"Sides pe 3 number, upar scissors, style ke liye thodi length rakho, neckline taper kar do, edges saaf kar do.\"",
        "barber_b1" to "Jo cut chahiye uski photo le ja — har naai shabd alag samajhta hai.",
        "barber_b2" to "Beech me gadbad lage to tabhi bol — baad me nahi.",
        "curly_title" to "Curly baalon ka playbook",
        "curly_sub" to "Curls ko alag routine chahiye, zyada products nahi.",
        "curly_b0" to "Hafte me 2 baar sulfate-free shampoo se dho — roz dhone se curls dry hote hain.",
        "curly_b1" to "Har wash pe conditioner, phir halke geele baalon pe leave-in conditioner.",
        "curly_b2" to "Sookhe curls kabhi brush mat kar — geele me ungliyon ya moti kanghi se suljha.",
        "curly_b3" to "Raat ko satin ke takiye pe so — subah ka frizz kam hoga.",
        "curly_b4" to "Kam heat, zyada patience — curls consistency ka inaam dete hain.",
        "style_title" to "5-minute styling routine",
        "style_sub" to "Daily ka minimum jo sach me kaam karta hai.",
        "style_s0" to "Halke geele baal",
        "style_s0d" to "Towel se ponchhe, halke geele baalon se shuru kar — na bheega, na sookha.",
        "style_s1" to "Matar-dana product",
        "style_s1d" to "Texture ke liye matte clay, neat look ke liye cream. Soch se kam le.",
        "style_s2" to "Blow direction",
        "style_s2d" to "Jis direction me baal baithane hain usi me blow-dry kar — heat shape set karti hai.",
        "style_s3" to "Finish",
        "style_s3d" to "Kanghi nahi, ungliyon se style kar — natural finish. Ho gaya.",
        "hair_shape_oval" to "Zyadatar cuts chalenge — proportions pehle se balanced hain. Textured crop ya clean side part, jo hai usse lad mat.",
        "hair_shape_round" to "Upar height, sides pe fade chhota. Bowl cut aur gaalon pe width badhane wale cuts se bach.",
        "hair_shape_square" to "Upar texture aur messy fringe se angles soft kar. Bahut chhota buzz jaw ko aur boxy dikhata hai.",
        "hair_shape_oblong" to "Upar extra height se bach. Side part aur bhare hue sides face ko lamba lagne se rokte hain.",
        "hair_shape_heart" to "Jaw ke aas-paas volume chaude maathe ko balance karta hai. Textured fringe, medium length.",
        "hair_shape_diamond" to "Fringe ke saath maathe aur jawline pe width. Sides pe chipke hue cuts se bach.",

        "caps_skin" to "SKIN QUIZ",
        "skinq_title" to "Apna 3-step routine dhoondh",
        "skinq_sub" to "Har sawal pe ek option tap kar — 20 second lagenge.",
        "sq0" to "Dopahar tak teri skin…",
        "sq0_o0" to "Chipchipi / oily",
        "sq0_o1" to "Khichi hui",
        "sq0_o2" to "Sirf T-zone pe shiny",
        "sq0_o3" to "Comfortable",
        "sq1" to "Teri skin jaldi react karti hai?",
        "sq1_o0" to "Haan — aksar laal / khujli hoti hai",
        "sq1_o1" to "Kabhi kabhi",
        "sq1_o2" to "Nahi, bilkul chill",
        "sq2" to "Kitni baar daane nikalte hain?",
        "sq2_o0" to "Aksar",
        "sq2_o1" to "Kabhi kabhi",
        "sq2_o2" to "Rarely",
        "sq3" to "Normal din me dhoop kitni?",
        "sq3_o0" to "Zyadatar indoors",
        "sq3_o1" to "1-2 ghante bahar",
        "sq3_o2" to "Lambe ghante bahar",
        "sq4" to "Poore routine ka budget?",
        "sq4_o0" to "₹300 se kam",
        "sq4_o1" to "₹300-800",
        "sq4_o2" to "₹800+",
        "skin_result_title" to "TERA 3-STEP",
        "skin_result_sub" to "Subah + raat. Roz wahi teen steps.",
        "skin_step_cleanser" to "Cleanser",
        "skin_step_moist" to "Moisturizer",
        "skin_step_spf" to "SPF 30+",
        "skin_cleanser_oily" to "Gel ya halka foaming cleanser — bhari cream wash chhod de.",
        "skin_cleanser_dry" to "Gentle cream ya milky cleanser — foaming 'deep clean' walon se door reh.",
        "skin_cleanser_combo" to "Gentle gel cleanser — T-zone ke liye halka, gaalon ke liye narm.",
        "skin_cleanser_normal" to "Koi bhi gentle cleanser — simple rakh.",
        "skin_moist_oily" to "Halka gel moisturizer — bhari creams chhod de.",
        "skin_moist_dry" to "Rich cream moisturizer — teri skin pi jayegi.",
        "skin_moist_combo" to "Halka lotion ya gel-cream texture.",
        "skin_moist_normal" to "Ek basic halka moisturizer.",
        "skin_spf_high" to "Roz subah SPF 30+, bahar har 3 ghante me dobara — saath leke chal.",
        "skin_spf_sensitive" to "Roz subah SPF 30+ — skin react kare to fragrance-free le.",
        "skin_spf_default" to "Roz subah SPF 30+ — skincare ka sabse high-ROI step.",
        "skin_extra_sensitive" to "Sab kuch fragrance-free — teri skin fragrance ko na bolti hai.",
        "skin_extra_acne" to "Boring rakh: cleanser, moisturizer, SPF. Zyada products ka matlab tez clear skin nahi — lagatar daane dermatologist ka kaam hain, aur serums ka nahi.",
        "skin_extra_budget" to "Budget route: ek gentle cleanser + ek moisturizer + ek sunscreen = poora routine. Basics roz hone tak serums chhod de.",
        "retake_quiz" to "Quiz phir se",
        "spf_title" to "Desi no-white-cast sunscreen guide",
        "spf_sub" to "Brown skin pe sunscreen ashy kyun lagta hai — aur kaise bachein.",
        "spf_b0" to "Chemical vs mineral: chemical filters UV absorb karte hain aur aam taur pe invisible blend hote hain; mineral filters (zinc, titanium) upar baithte hain aur light reflect karte hain — wahi safed layer cast hai.",
        "spf_b1" to "Brown skin pe chemical ya hybrid gel sunscreen gayab ho jate hain. Mineral-only wale lagbhag hamesha grey/white cast chhodte hain.",
        "spf_b2" to "Bahar ho to har 3 ghante me dobara laga — subah ki ek layer din bhar nahi tikti.",
        "spf_b3" to "Indian-market tips: 'no white cast' likhe gel sunscreen dhoondh; moti safed creams chhod de jab tak label na kahe; 50g ki tube roz ke face use me lagbhag ek mahina chalti hai.",

        "caps_debloat" to "DEBLOAT PROTOCOL",
        "debloat_sub" to "Face ki puffiness kam karne ka 7-din ka subah plan. Checklist kholne ke liye din pe tap kar.",
        "debloat_d0t" to "Paani reset",
        "debloat_d0i0" to "Uthte hi 500ml paani pi",
        "debloat_d0i1" to "Aaj no achaar / pickles",
        "debloat_d0i2" to "Sone se 3 ghante pehle dinner khatm",
        "debloat_d1t" to "Namak audit",
        "debloat_d1i0" to "Aaj papad aur instant noodles skip kar",
        "debloat_d1i1" to "Ek namkeen packet ka sodium label padh — hosh ud jayenge",
        "debloat_d1i2" to "Har meal ke saath paani pi",
        "debloat_d2t" to "Potassium day",
        "debloat_d2i0" to "Kela kha aur nariyal paani pi",
        "debloat_d2i1" to "Ek meal me palak daal",
        "debloat_d2i2" to "Aaj bahar ka khana nahi",
        "debloat_d3t" to "Neend push",
        "debloat_d3i0" to "Aaj raat 8 ghante so",
        "debloat_d3i1" to "4 baje ke baad no chai / coffee",
        "debloat_d3i2" to "Sone se 3 ghante pehle aakhri meal",
        "debloat_d4t" to "Lymph day",
        "debloat_d4i0" to "Subah 5-min lymphatic massage: jaw se halke strokes → gardan se neeche → collarbones tak",
        "debloat_d4i1" to "Uske baad thande paani se muh dho",
        "debloat_d4i2" to "Aaj namak kam rakh",
        "debloat_d5t" to "Restaurant rules",
        "debloat_d5i0" to "Bahar khaye to: bhari gravy chhod, kam namak bol",
        "debloat_d5i1" to "Dinner me dahi + kheera",
        "debloat_d5i2" to "Dinner ke baad 15 min walk",
        "debloat_d6t" to "Photo check-in",
        "debloat_d6i0" to "Day 1 wali lighting aur angle me photo le",
        "debloat_d6i1" to "Compare kar — jo kaam kiya use daily habit bana",
        "debloat_d6i2" to "Ye seekhne ka plan hai, crash plan nahi — debloat aadat hai, ek hafta nahi",
        "sod_title" to "Desi Sodium Guide",
        "sod_sub" to "Namak desi staples me chhupa hai — yahan dekho.",
        "sod_high" to "HIGH SODIUM — halka haath",
        "sod_h0" to "Achaar / pickles — ek chammach me aadhe din ka namak ho sakta hai",
        "sod_h1" to "Papad — seka ya tala, dono namak ke bomb hain",
        "sod_h2" to "Instant noodles — masala sachet hi villain hai",
        "sod_h3" to "Chips & namkeen — packet se mat kha, portion nikaal",
        "sod_h4" to "Restaurant gravy — makkhan aur namak se bhari",
        "sod_low" to "DEBLOAT FRIENDLY — zyada kha",
        "sod_l0" to "Kela — potassium extra sodium bahar nikaalne me help karta hai",
        "sod_l1" to "Nariyal paani — hydration + potassium",
        "sod_l2" to "Palak — potassium-rich, namak kam",
        "sod_l3" to "Dahi — halka, digestion shaant rakhta hai",
        "sod_l4" to "Kheera — paani se bhara aur cooling",

        "caps_posture" to "POSTURE CHALLENGE",
        "posture_sub" to "Forward head posture fix karne ke 30 din — silent jawline killer. Hafte complete hote hi tick kar.",
        "posture_w0" to "Hafta 1 — Foundation",
        "posture_w0i0" to "Chin tucks: 10 reps × 5-second hold, roz",
        "posture_w0i1" to "Screen eye level pe utha — phone pe gardan jhukana band",
        "posture_w0i2" to "Jab sir aage nikle, use wapas kheench",
        "posture_w1" to "Hafta 2 — Open up",
        "posture_w1i0" to "Chin tucks roz jaari rakh",
        "posture_w1i1" to "Wall angels: 3 × 10 — peeth deewar se chipka ke",
        "posture_w1i2" to "Har ghante kandhe seedhe kar",
        "posture_w2" to "Hafta 3 — Chest reset",
        "posture_w2i0" to "Doorway chest stretch: har side 2 × 30s",
        "posture_w2i1" to "Screen eye level pe — Hafta 1 wali aadat",
        "posture_w2i2" to "Ho sake to seedha let ke so",
        "posture_w3" to "Hafta 4 — Lock it in",
        "posture_w3i0" to "Roz full combo: chin tucks + wall angels + doorway stretch",
        "posture_w3i1" to "Ab posture maintenance hai — mushkil to shuru karna tha",
        "posture_foot" to "Poori habit tracking Routine tab me hai — ye challenge plan hai.",

        "caps_season" to "COLOR SEASON",
        "season_title" to "Apna season dhoondh",
        "season_sub" to "3 sawal — wo colors pehno jo teri skin ko zinda dikhayein.",
        "season_q0" to "Dhoop me kalai ki nasen dekh",
        "season_q0w" to "Hari lagti hain",
        "season_q0c" to "Neeli / purple lagti hain",
        "season_q1" to "Tujhpe kaunsa jewelry better lagta hai?",
        "season_q1w" to "Gold",
        "season_q1c" to "Silver",
        "season_q2" to "Dhoop me kya hota hai?",
        "season_q2w" to "Aaram se tan hota hai",
        "season_q2c" to "Pehle jalta hai",
        "season_you_are" to "Tu hai {s}",
        "season_tagline_autumn" to "Warm, deep, earthy — rich tones me tu chamakta hai.",
        "season_tagline_winter" to "Cool, bold, high-contrast — black aur jewel tones tere hain.",
        "season_tagline_spring" to "Warm, bright, fresh — halke punchy colors tujhe uthate hain.",
        "season_tagline_summer" to "Cool, soft, muted — powdery pastels tujhpe best lagte hain.",
        "season_tagline_neutral" to "Tu warm aur cool ke beech hai — dono taraf se le aur wahi pehen jisme pehle se tareef milti hai.",
        "season_name_autumn" to "Autumn",
        "season_name_winter" to "Winter",
        "season_name_spring" to "Spring",
        "season_name_summer" to "Summer",
        "season_name_neutral" to "Beech wala",
        "caps_desi_palette" to "DESI PALETTE",
        "season_tip" to "Pehle apne palette ka ek piece chehre ke paas pehen — tee, kurta, shirt. Dhoop me dekh skin kaisi lag rahi hai.",
        "swatch_title" to "Swatch test — honest drape",
        "swatch_b0" to "Dhoop me khidki ki taraf muh karke khade ho. Thhodi ke neeche solid-color kapda pakdo — warm test ke liye mustard ya peela, cool test ke liye grey ya neela.",
        "swatch_b1" to "Jawline ki shadows aur skin dekho: shadows tez hon aur skin zinda lage to wahi temperature tera hai. Skin dull ya grey lage to wo tera nahi. Do kapde, do minute — koi app filter ye fake nahi kar sakta.",
        "caps_color_season" to "TERA COLOR SEASON",
        "season_locked" to "Abhi undertone read nahi hua — palette unlock karne ke liye Guides tab me 3-sawal wala season quiz de.",
        "caps_softmaxx" to "SOFTMAXX GUIDES",
        "softmaxx_sub" to "Moggr ke saare recommended methods, seedhe shabdon me. Padhne ke liye guide pe tap kar.",

        "cam_analyze" to "Mera face analyze kar",
        "cam_retake" to "Dobara le",
        "cam_analyzing" to "Tera face analyze ho raha hai",

        "caps_face_report" to "FACE REPORT",
        "sec_feature_scores" to "Feature scores",
        "sec_positives" to "Positives",
        "sec_negatives" to "Negatives",
        "sec_ascension" to "Ascension plan",
        "sec_summary" to "Summary",
        "result_next" to "AAGE",
        "face_map" to "Face map"
    )

    // ---------- guide titles + bodies, keyed by English title ----------
    private val GUIDE_TITLES_HI = mapOf(
        "Beard density routine" to "Daadhi ghani karne ka routine",
        "Fragrance basics" to "Fragrance basics",
        "Under-chin tightening drill" to "Thhodi ke neeche tightening drill",
        "Sleep for your face" to "Face ke liye neend",
        "Neck training" to "Gardan ki training",
        "Tongue posture & chewing" to "Jeebh ki posture aur chabana",
        "Fix forward head posture" to "Forward head posture fix kar",
        "Clean bulking" to "Clean bulking",
        "Scalp care" to "Scalp care",
        "Voice drills" to "Voice drills",
        "Eyebrow grooming basics" to "Eyebrow grooming basics",
        "Smile & teeth basics" to "Smile aur daant basics",
        "30-day jawline program" to "30-din ka jawline program",
        "Chewing for tone" to "Tone ke liye chabana"
    )

    private val GUIDE_BODIES_HI = mapOf(
        "Beard density routine" to "Jawline aur gaalon pe ungliyon se roz 3-5 minute massage kar — follicles me blood flow badhta hai. Protein wala khana kha, 7-9 ghante so, aur daadhi ke neeche ki skin saaf rakh taaki follicles block na hon. Pehle visible gains 4-6 hafte me, asli coverage 3-6 mahine me. Koi product tere liye kaam nahi karega — consistency karegi.",
        "Fragrance basics" to "Pulse points pe ek ya do spray — gardan ke sides aur kalai. Kam hi zyada hai: paas aane pe hi mehek aani chahiye. Din ke liye fresh ya citrus, shaam ke liye woody ya spicy. Paanch alag scents mat mila; ek chun aur use dhang se pehen.",
        "Under-chin tightening drill" to "Poori jeebh taalu se chipka, phir jaw dheere aur jitna aaram se khule utna khol, aur band kar. Roz 2 baar, 3 sets of 10. Kuch hafton me thhodi ke neeche ki muscles tight hoti hain aur throat-to-jaw angle saaf dikhta hai. Jaw click kare, dard ho ya lock ho to turant ruk ja — kabhi zor mat laga.",
        "Sleep for your face" to "Fixed time pe 7-9 ghante so — puffy eyes aur dull skin aam taur pe pehle neend ki problem hoti hai. Uthne ke 30 minute me dhoop le taaki body clock set ho, raat ko lights dim kar, kamra andhera aur thanda rakh, aur sone se 3-4 ghante pehle khana band.",
        "Neck training" to "Moti gardan jaw ko frame karti hai aur silhouette chauda dikhta hai. Neck curls: seedha let ke thhodi ko seene ki taraf la, 3 sets of 15, hafte me 2 baar. Traps ke liye dumbbell shrugs aur farmer carries daal. Pehle gardan ke dheere circles se warm-up kar, motion controlled rakh, dard me kabhi train mat kar, aur hafte me 2-3 session se zyada nahi.",
        "Tongue posture & chewing" to "Poori jeebh taalu pe tika, honth band, naak se saans — poora din, roz. Ek taraf se mat chaba, dono sides barabar; sakht khana ya 10-15 minute gum roz jaw ki muscles tone karta hai. Posture ki aadatein mahinon me compound hoti hain, dinon me nahi.",
        "Fix forward head posture" to "Sir aage nikalne se jawline gayab ho jati hai. Deewar se peeth chipka ke khade ho, thhodi seedhi peeche kheench jaise double chin bana rahe ho, 5 second hold, roz 10-15 baar. Screen eye level pe rakh, neeche dekhna band, aur ho sake to seedha let ke so.",
        "Clean bulking" to "Face phulaye bina size badhane ke liye: maintenance se lagbhag 200-300 kcal zyada kha, bodyweight ke hisab se lagbhag 2g protein per kg le, aur hafte me 2-4 baar bade compound lifts progressive overload ke saath kar. Ganda bulk pehle face me dikhta hai aur wapas aane me mahine lagte hain — frame bana, fat nahi.",
        "Scalp care" to "Hafte me 2-3 baar gentle shampoo se dho — zyada dhone se scalp strip hota hai aur baal zyada jhadte hain. Roz 5 minute ungliyon se scalp massage kar taaki blood flow badhe. Tools saaf rakh, khujla ya ragad mat, aur har mahine same lighting me photos se progress track kar.",
        "Voice drills" to "Seene se nahi, pet se saans le: kandhe hilaye bina pet phoolne de jab saans le. Din bhar paani pi aur seedha khada reh taaki gala khula rahe. Roz 5 minute zor se padh — steady, shaant pace pe — aur khud ko record kar — kuch hafton me farak sunai dega.",
        "Eyebrow grooming basics" to "Brows ko saaf spoolie ya purane toothbrush se seedha upar brush kar. Jo baal natural brow line se bahut bahar nikle, chhoti scissors se trim kar — upar comb kar, sirf tips kaat. Arch ke neeche ke obvious strays ek ek karke tweeze kar, beech me peeche hat ke dekh. Teri natural arch hi blueprint hai — nayi shape mat bana. Zyada ukhadi brows wapas aane me mahine lagte hain, to soch se kam le.",
        "Smile & teeth basics" to "Din me 2 baar poore 2 minute brush kar, sone se pehle floss, aur jeebh brush kar — badbu zyadatar wahin rehti hai. Dard na bhi ho to saal me 2 baar dentist ke paas ja. Coffee ya chai ke baad paani se kulla kar taaki daag na jammein. Chemical whitening strips aur DIY bleach hacks chhod de — enamel kharab karte hain. Saaf daant safed daanton se behtar.",
        "30-day jawline program" to "Plan: hafte me 4 din sugar-free gum 10-15 minute; under-chin drill roz; neck curls hafte me 2 baar. TMJ SAFETY — pehle ye padh: jaw click kare, dard ho ya lock ho to turant ruk aur kuch din rest de. Jaw ko kabhi zor se mat khol ya dard me mat pees. Ek hafte me na theek hone wala jaw pain dentist ka kaam hai, aur zyada mehnat ka nahi. Ye mahinon me muscle tone banata hai — haddi nahi badalta, aur jo 30-din me bone change ka daava kare wo jhooth bol raha hai.",
        "Chewing for tone" to "Dono sides barabar chaba — ek taraf se chabane se ek side zyada banti hai. Meals ke beech jeebh taalu pe rakh aur naak se saans le. Hafte me kuch baar sakht khana ya gum masseters ko active rakhta hai. Honest framing: ye mahinon me muscle tone aur tez look banata hai. Jawbone reshape nahi karta. Posture aur kam face bloat kisi bhi chew count se zyada matter karte hain."
    )

    /** Combined tables: s()/fmt() consult these. */
    private val ALL_EN: Map<String, String> = EN + EN2 + EN3 + EN4 + EN5 + EN6 + EN7
    private val ALL_HI: Map<String, String> = HI + HI2 + HI3 + HI4 + HI5 + HI6 + HI7

    /** Hinglish title for a guide, keyed by its English title. Falls back to English. */
    fun guideTitle(title: String, hi: Boolean): String =
        if (hi) GUIDE_TITLES_HI[title] ?: title else title

    /** Hinglish body for a guide, keyed by its English title. Falls back to English. */
    fun guideBody(body: String, title: String, hi: Boolean): String =
        if (hi) GUIDE_BODIES_HI[title] ?: body else body
}

    // ---------- phases + measurements (v2.6 additions) ----------
    private val EN3 = mapOf(
        "phase_t_foundation" to "Foundation",
        "phase_t_frame" to "Frame",
        "phase_t_finish" to "Finish",
        "phase_g_foundation" to "Skin clears up, sleep locks in, habits go automatic.",
        "phase_g_frame" to "Neck thicker, posture taller, hair dialed in.",
        "phase_g_finish" to "Style locked, photo-ready, posture on autopilot.",
        "phase_w0" to "Week 1 — AM/PM cleanse every single day",
        "phase_w1" to "Week 2 — SPF 30+ every morning, no skips",
        "phase_w2" to "Week 3 — 2L water + cut the junk food",
        "phase_w3" to "Week 4 — in bed by 11, same time nightly",
        "phase_w4" to "Week 5–6 — neck curls 3x a week",
        "phase_w5" to "Week 7 — chin tucks daily, fix the forward head",
        "phase_w6" to "Week 8 — haircut that fits your face shape",
        "phase_w7" to "Week 9 — basics check: fits that actually fit",
        "phase_w8" to "Week 10 — grooming day: brows, nails, lineup",
        "phase_w9" to "Week 11–12 — photo practice under the same light",
        "meas_0_name" to "Symmetry",
        "meas_0_desc" to "Left-right balance of the whole face.",
        "meas_1_name" to "Facial thirds",
        "meas_1_desc" to "Forehead, midface and lower face in balance.",
        "meas_2_name" to "Facial fifths",
        "meas_2_desc" to "Face width split into five equal eye-widths.",
        "meas_3_name" to "Midface ratio",
        "meas_3_desc" to "How compact the middle of the face is.",
        "meas_4_name" to "Eye spacing (ESR)",
        "meas_4_desc" to "Distance between the eyes vs face width.",
        "meas_5_name" to "FWHR",
        "meas_5_desc" to "Face width vs height.",
        "meas_6_name" to "Eyes",
        "meas_6_desc" to "Shape, tilt and openness.",
        "meas_7_name" to "Nose",
        "meas_7_desc" to "Width and proportion against the face.",
        "meas_8_name" to "Lips",
        "meas_8_desc" to "Fullness and width balance.",
        "meas_9_name" to "Jawline",
        "meas_9_desc" to "Width and definition.",
        "meas_10_name" to "Chin",
        "meas_10_desc" to "Projection and width.",
        "meas_11_name" to "Brows",
        "meas_11_desc" to "Density and shape framing the eyes.",
        "meas_12_name" to "Cheekbones",
        "meas_12_desc" to "Width and prominence.",
        "meas_13_name" to "Jaw angle",
        "meas_13_desc" to "Frontal sharpness of the jaw corners.",
        "meas_14_name" to "Side profile",
        "meas_14_desc" to "Chin projection read from your side photo."
    )

    private val HI3 = mapOf(
        "phase_t_foundation" to "Foundation",
        "phase_t_frame" to "Frame",
        "phase_t_finish" to "Finish",
        "phase_g_foundation" to "Skin clear, neend set, aadatein automatic.",
        "phase_g_frame" to "Gardan moti, posture lamba, baal set.",
        "phase_g_finish" to "Style locked, photo-ready, posture autopilot.",
        "phase_w0" to "Hafta 1 — roz subah/shaam cleanse, ek din bhi miss nahi",
        "phase_w1" to "Hafta 2 — roz subah SPF 30+, no skip",
        "phase_w2" to "Hafta 3 — 2L paani + junk food band",
        "phase_w3" to "Hafta 4 — 11 baje tak bistar, roz same time",
        "phase_w4" to "Hafta 5-6 — hafte me 3 baar neck curls",
        "phase_w5" to "Hafta 7 — roz chin tucks, forward head fix kar",
        "phase_w6" to "Hafta 8 — face shape pe suit karne wala haircut",
        "phase_w7" to "Hafta 9 — basics check: fit jo actually fit ho",
        "phase_w8" to "Hafta 10 — grooming day: brows, nails, lineup",
        "phase_w9" to "Hafta 11-12 — same light me photo practice",
        "meas_0_name" to "Symmetry",
        "meas_0_desc" to "Poore face ka left-right balance.",
        "meas_1_name" to "Facial thirds",
        "meas_1_desc" to "Maatha, midface aur lower face ka balance.",
        "meas_2_name" to "Facial fifths",
        "meas_2_desc" to "Face width ko paanch barabar eye-widths me baanta.",
        "meas_3_name" to "Midface ratio",
        "meas_3_desc" to "Face ka beech wala hissa kitna compact hai.",
        "meas_4_name" to "Eye spacing (ESR)",
        "meas_4_desc" to "Aankhon ke beech ki doori vs face width.",
        "meas_5_name" to "FWHR",
        "meas_5_desc" to "Face width vs height.",
        "meas_6_name" to "Eyes",
        "meas_6_desc" to "Shape, tilt aur openness.",
        "meas_7_name" to "Nose",
        "meas_7_desc" to "Width aur face ke against proportion.",
        "meas_8_name" to "Lips",
        "meas_8_desc" to "Fullness aur width ka balance.",
        "meas_9_name" to "Jawline",
        "meas_9_desc" to "Width aur definition.",
        "meas_10_name" to "Chin",
        "meas_10_desc" to "Projection aur width.",
        "meas_11_name" to "Brows",
        "meas_11_desc" to "Density aur shape jo eyes ko frame karte hain.",
        "meas_12_name" to "Cheekbones",
        "meas_12_desc" to "Width aur prominence.",
        "meas_13_name" to "Jaw angle",
        "meas_13_desc" to "Jaw corners ki frontal sharpness.",
        "meas_14_name" to "Side profile",
        "meas_14_desc" to "Side photo se chin projection."
    )

    // ---------- v2.6 coach-extras additions ----------
    private val EN4 = mapOf(
        "coach_milestone" to "New milestone",
        "coach_checkin_sub" to "30 seconds — the coach uses this in today's advice.",
        "coach_puff_scale" to "1 = tight, 5 = balloon",
        "coach_start" to "Start →",
        "vibe_short_blunt" to "Blunt",
        "vibe_short_bigbro" to "Big bro",
        "vibe_short_hype" to "Hype",
        "focus_opt_0" to "skin",
        "focus_opt_1" to "hair",
        "focus_opt_2" to "posture",
        "focus_opt_3" to "debloat"
    )

    private val HI4 = mapOf(
        "coach_milestone" to "Naya milestone",
        "coach_checkin_sub" to "30 second — coach aaj ki advice me ye use karega.",
        "coach_puff_scale" to "1 = tight, 5 = phula hua",
        "coach_start" to "Shuru kar →",
        "vibe_short_blunt" to "Seedha",
        "vibe_short_bigbro" to "Bade bhai",
        "vibe_short_hype" to "Hype",
        "focus_opt_0" to "skin",
        "focus_opt_1" to "baal",
        "focus_opt_2" to "posture",
        "focus_opt_3" to "debloat"
    )

    // ---------- v2.6 report additions ----------
    private val EN5 = mapOf(
        "score_of" to "{n}'s score",
        "your_score" to "Your score"
    )

    private val HI5 = mapOf(
        "score_of" to "{n} ka score",
        "your_score" to "Tera score"
    )

    // ---------- v2.6 flow-dialog chrome ----------
    private val EN6 = mapOf(
        "flow_close" to "✕ Close",
        "flow_step" to "Step {i} of {n}",
        "flow_review" to "Review",
        "flow_back" to "‹ Back",
        "flow_edit" to "‹ Edit"
    )

    private val HI6 = mapOf(
        "flow_close" to "✕ Band kar",
        "flow_step" to "Step {i} of {n}",
        "flow_review" to "Review",
        "flow_back" to "‹ Peeche",
        "flow_edit" to "‹ Badal"
    )

    // ---------- v2.6 report subtitles ----------
    private val EN7 = mapOf(
        "sub_feature_scores" to "Every measurement, scored 1–8 against community ideals",
        "sub_positives" to "Your best features — what carries the rating",
        "sub_negatives" to "Biggest deductions — fix these first",
        "sub_ascension" to "Ordered fixes for your weakest features — no surgery, ever",
        "sub_face_map" to "Proportional guides — not landmark-anchored"
    )

    private val HI7 = mapOf(
        "sub_feature_scores" to "Har measurement, 1–8 community ideals pe scored",
        "sub_positives" to "Tere best features — jo rating ko uthate hain",
        "sub_negatives" to "Sabse bade deductions — inhe pehle fix kar",
        "sub_ascension" to "Weakest features ke ordered fixes — surgery kabhi nahi",
        "sub_face_map" to "Proportional guides — landmark-anchored nahi"
    )
